language: generic

dist: bionic

services:
  - docker

matrix:
  include:
    - language: csharp
      before_script:
        - cd src/services/PaymentService/
      script:
        - dotnet restore
        - dotnet build