language: generic

dist: bionic

services:
  - docker

matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 2.2
      before_script:
        - cd src/services/PaymentService/api/src
      script:
        - dotnet restore
        - dotnet build